### ISSUE TITLE
Add optional parameters to RUM snippets

### ISSUE THREAD

**Issue by kimsauce** [SumoLogic/sumologic-documentation#1517]
Service is the only parameter shown in RUM snippets because it's mandatory (rest are optional). 

We can add `application` and `environment` to make it more complete, but we should do that in all places, including https://github.com/SumoLogic/sumologic-opentelemetry-js and all methods (Synchronous, Asynchronous, NPM). If you have the time for that - go ahead and please work with dev team.

_Originally posted by @pbrzoska-sumo in https://github.com/SumoLogic/sumologic-documentation/pull/1414#discussion_r1085515997_

**Comment by jpipkin1** [comment]
Here is the section to be updated: 
https://help.sumologic.com/docs/apm/real-user-monitoring/configure-data-collection/#step-2-add-rum-script-to-your-page-header

**Comment by jpipkin1** [comment]
@kimsauce, I'm closing this ticket because I don't believe we need to add the optional parameters for `application` and `deploymentEnvironment` to the script examples. They are just two of the many [parameters](https://github.com/SumoLogic/sumologic-opentelemetry-js?tab=readme-ov-file#configuration) you can add to the script, and I see no reason to add them. If you disagree, you can always reopen the ticket and assign it to me.

**Comment by kimsauce** [comment]
> @kimsauce, I'm closing this ticket because I don't believe we need to add the optional parameters for `applicationName` and `deploymentEnvironment` to the script examples. They are just two of the many [parameters](https://github.com/SumoLogic/sumologic-opentelemetry-js?tab=readme-ov-file#configuration) you can add to the script, and I see no reason to add them. If you disagree, you can always reopen the ticket and assign it to me.

Agreed! @jpipkin1 Many thanks for looking into this.
