### ISSUE TITLE
Generate CSE Signals With a Scheduled Search - add field order

### ISSUE THREAD

**Issue by kostuch-sumologic** [SumoLogic/sumologic-documentation#1803]
**Describe the bug:**
For the Generate CSE Signals With a Scheduled Search page, the location of the Required Fields in the query should be included.  

**Steps to reproduce the behavior:**
https://help.sumologic.com/docs/alerts/scheduled-searches/generate-cse-signals/

**Expected behavior:**
The required fields (normalizedseverity, stage, entity) need to come after the **where** and **count** operators, otherwise an error will occur when saving the scheduled search.  

**Screenshots**
correct query order example
![Screenshot 2023-03-06 at 12 53 31 PM](https://user-images.githubusercontent.com/106690344/223191839-18f86f6f-b90e-43d2-b5ab-5f5947259a84.png)

**Comment by jpipkin1** [comment]
@kostuch-sumologic, would it be adequate to simply add your guidance as a note after step 1 in the "[Scheduling a search](https://help.sumologic.com/docs/alerts/scheduled-searches/generate-cse-signals/#scheduling-the-search)" section?

Note: 
The required fields (`normalizedseverity`, `stage`, and for Entities) need to come after the `where` and `count` operators, otherwise an error will occur when saving the scheduled search.

**Comment by jpipkin1** [comment]
@kostuch-sumologic responded in Slack: 
"I like that update."

**Comment by jpipkin1** [comment]
The note is added:
https://help.sumologic.com/docs/alerts/scheduled-searches/generate-cse-signals/#scheduling-the-search
