### ISSUE TITLE
Add specific example of a custom threat intel feed to the threat intel support documentation

### ISSUE THREAD

**Issue by kostuch-sumologic** [SumoLogic/sumologic-documentation#2272]
**Is your feature request related to a problem? Please describe.**
Add specific example of a custom threat intel feed to the threat intel support documentation. 
https://help.sumologic.com/docs/cse/rules/about-cse-rules/#threat-intel

**Describe the solution you'd like:**
Consider using the CISA feed for examples.
https://www.cisa.gov/topics/cyber-threats-and-advisories/information-sharing/automated-indicator-sharing-ais

**Additional info:**
This is a customer request.  GDIT is in the federal space and makes extensive use of threat intel feeds.  

GDIT
Organization ID
0000000000015E9F

**Comment by jpipkin1** [comment]
@kostuch-sumologic, I will make the update to this following article instead of "[About CSE Rules](https://help.sumologic.com/docs/cse/rules/about-cse-rules/#threat-intel)", since it is the main article where we document threat intelligence:
https://help.sumologic.com/docs/cse/administration/create-custom-threat-intel-source/
