### ISSUE TITLE
Algolia : Parse not first result in parse operator search

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/sumologic-documentation#2752]
Feedback from UX -- I was searching for the term “Parse”, hoping to find information about the log search parse operator. The top results,, did not show the “parse field option” which was the one I was looking for and I think is the most relevant result,. Instead, the result showed items like ParseHex, ParseDate,… Hitting the Enter key, lead me to the first item in the results.

**Comment by kimsauce** [comment]
Thanks for logging the ticket, @stacykor ! To set parse to the no. 1 result, we'll need the Rules upgrade. I've set a meeting for us w/Algolia next week to discuss.

**Comment by jpipkin1** [comment]
This problem is now fixed with a rule in Algolia. Typing "parse" in the search field now returns this article as the first result: https://help.sumologic.com/docs/search/search-query-language/parse-operators/

To see the rule, go to: https://dashboard.algolia.com/apps/2SJPGMLW1Q/rules/crawler_sumodocs?query=parse
