### ISSUE TITLE
Multiple pages are showing 404 errors - When searching the documentation page, many results display in the drop-down. Last few weeks I'm seeing multiple documents resulting in 404 pages - including the ones in the screenshots. 

### ISSUE THREAD

**Issue by lljgit** [SumoLogic/sumologic-documentation#3126]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.

**Steps to reproduce the behavior:**
1. Click on '...'
1. Scroll down to '...'
1. See error

**Expected behavior:**
Describe what you expected to happen.

**Screenshots**

**Desktop/Tablet/Smartphone (please complete the following information):**

**Additional info:**

**Comment by lljgit** [comment]
<img width="1220" alt="Screenshot 2023-09-28 at 11 36 06 AM" src="https://github.com/SumoLogic/sumologic-documentation/assets/104160884/d63e51d3-cc08-462d-bcdd-6c079ca16649">

**Comment by jpipkin1** [comment]
@lljgit, the URL shown in your screenshot above indicates you are attempting to run the help from a temporary build (e.g. xsa.cloudfront.net) rather than our production online help (help.sumologic.com). If you attempt to access the Amazon Cognito article from our production online help, you'll find that it works:
https://help.sumologic.com/docs/integrations/amazon-aws/amazon-cognito/

**Comment by lljgit** [comment]
Thanks! I thought the URL looked weird. I’m accessing from inside the sumo
network. Not sure how I ended up on the temp build.

**Comment by jpipkin1** [comment]
@lljgit, I'll close this issue. But if you encounter any other problems, don't hesitate to create issues as needed, or contact us at the #dochub Slack channel.
