### ISSUE TITLE
Feature Request: Customizable Chart Colors/Palette

### ISSUE THREAD

**Issue by Zixer1** [SumoLogic/sumologic-documentation#4204]
**Is your feature request related to a problem? Please describe.**

The problem we have is we can't specifically choose the colors for chart items. For example, we have compliance check reports that would require specific colors for better visibility, somthing like red for failed checks and green/blue for passed checks. With the current color palette, it's impossible to achieve this. The documentation indicates that manually choosing a specific color for the chart, as well as specific colors for the Pie chart, is not possible.

**Describe the solution you'd like:**

We would like to have the ability to modify colors for individual elements within charts, such as setting red for failed compliance checks and green/blue for passed checks. Or what could also work is if we could make Custom color palettes 

**Describe alternatives you have considered:**

Using predefined color palettes, which do not offer the specific color control needed for compliance checks. Havn't considered more alternatives as it is a minor feature (although still important for visibility)

**Additional info:**

N/A

**Comment by jpipkin1** [comment]
Thanks for your comments, @Zixer1. 

I presume you are referring to the [Modify a Chart](https://help.sumologic.com/docs/dashboards/panels/modify-chart/#modifydisplay-settings) documentation. I will investigate whether it is possible to change colors for individual data points on charts, and if it is, we will add documentation for it.

**Comment by jpipkin1** [comment]
I'm tracking this issue with ticket [DOCS-280](https://sumologic.atlassian.net/browse/DOCS-280).

**Comment by jpipkin1** [comment]
@Zixer1, I contacted the development team, and they said you can choose colors for specific chart items using Display Overrides, which are documented in the "Modify a Chart" article:  https://help.sumologic.com/docs/dashboards/panels/modify-chart/#overridedashboard-displays

Take the example of this pie chart. Before applying any overrides, it looks like this:
<img width="997" alt="before-override" src="https://github.com/SumoLogic/sumologic-documentation/assets/127961815/3acde4bd-e3f6-4dba-a5bf-46c95fcb6545">

After applying an override to make the "Others" portion red, it looks like this:
<img width="995" alt="after-override" src="https://github.com/SumoLogic/sumologic-documentation/assets/127961815/dfe56008-b8ff-4149-87c6-6268ca0042bd">

I'll close this ticket, since documentation exists for your use case. If you have any more questions, please let us know.
